services:
  - type: web
    name: telegram-aliexpress-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
      - key: AFFILIATE_ID
      - key: RENDER_EXTERNAL_HOSTNAME
