services:
  - type: web
    name: telegram-aliexpress-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker main:app --timeout 15"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
      - key: RENDER_EXTERNAL_HOSTNAME

